# Generated by Django 3.1.2 on 2023-06-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seguimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimiento',
            name='fecha_pago',
        ),
    ]
